### ISSUE TITLE
Network / OpenStack

### ISSUE THREAD

**Issue by YouriT** [yadutaf/docker-machine-driver-ovh#27]
Nice driver. I was just wondering about 2 things:
- Why not using the OpenStack driver?
- Why didn't you implement anything about network connection ? Basically, here you let OVH do the job but you cannot join any existing private network(s) neither defining whether or not you want public network connectivity.

**Comment by yadutaf** [comment]
Thanks :)

The OpenStack driver will work. Actually, the first versions of this driver were a thin layer on top of the OpenStack driver. To use the OpenStack driver, you just need to create an OpenStack account in your Cloud console. Please note that some operations that were performed directly on OpenStack might no show up in the OVH control panel

Using the OVH API allows to share a single authentication scheme with all scripts using it. It also guarantees that all the actions performed via the API will show up in the control panel. For instance, when pushing an SSH key, it will automatically propagate it to all OpenStack regions so that they are ready to use on all zone.

Why nothing for private networks ? Never had the the time. But I accept pull requests :) What is your need ?

**Comment by YouriT** [comment]
Okay! Makes sense :)
I'm using Docker for a while and I was digging into the Public Cloud and didn't get why there was a driver on top as the underlying is OpenStack but it makes sense.

The need is pretty simple I must say, avoid exposing everything to the "world" and so being able to link multiple machines through a private network instead of the public one. How do you perform this action at the moment (if you do)? python-openstack I would guess? You don't have the need for other networks than the public one?

Will try to look at a PR for this feature even though I'm not confortable with Go but it might be feasible.

**Comment by yadutaf** [comment]
I think I would add a ``--ovh-private-network`` flag that would accept either an existing network name. This would match the project's behavior where the driver does not create a project for you. I must exist first.

If we are on a private network, we can just return the private IP to Docker. If we are one the public network, we will need to give Docker the public IP which may defeat the purpose of private networking... Maybe just return the private IP anyway and let docker-machine fail if it can not reach it ? Not sure what's the best here ?

I'm more of a C/Python developer. So, if it does not sound quite like Go, I might not even notice ^^

**Comment by yadutaf** [comment]
You can get the list of private networks with https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/network/private#GET and specify the additional networks as an array when creating the instance https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/instance#POST (I'd start with a single one anyway)

**Comment by kfletche** [comment]
Made some progress with this at #30.
